// Nomes de exibição por código de livro (USFM), em inglês e português.
// Inverso do mapa de parsing em referenceParser.ts (que normaliza para
// comparação, não para exibição).
export const BOOK_NAMES: Record<string, { en: string; pt: string }> = {
  GEN: { en: "Genesis", pt: "Génesis" },
  EXO: { en: "Exodus", pt: "Êxodo" },
  LEV: { en: "Leviticus", pt: "Levítico" },
  NUM: { en: "Numbers", pt: "Números" },
  DEU: { en: "Deuteronomy", pt: "Deuteronómio" },
  JOS: { en: "Joshua", pt: "Josué" },
  JDG: { en: "Judges", pt: "Juízes" },
  RUT: { en: "Ruth", pt: "Rute" },
  "1SA": { en: "1 Samuel", pt: "1 Samuel" },
  "2SA": { en: "2 Samuel", pt: "2 Samuel" },
  "1KI": { en: "1 Kings", pt: "1 Reis" },
  "2KI": { en: "2 Kings", pt: "2 Reis" },
  "1CH": { en: "1 Chronicles", pt: "1 Crónicas" },
  "2CH": { en: "2 Chronicles", pt: "2 Crónicas" },
  EZR: { en: "Ezra", pt: "Esdras" },
  NEH: { en: "Nehemiah", pt: "Neemias" },
  EST: { en: "Esther", pt: "Ester" },
  JOB: { en: "Job", pt: "Job" },
  PSA: { en: "Psalms", pt: "Salmos" },
  PRO: { en: "Proverbs", pt: "Provérbios" },
  ECC: { en: "Ecclesiastes", pt: "Eclesiastes" },
  SNG: { en: "Song of Songs", pt: "Cântico dos Cânticos" },
  ISA: { en: "Isaiah", pt: "Isaías" },
  JER: { en: "Jeremiah", pt: "Jeremias" },
  LAM: { en: "Lamentations", pt: "Lamentações" },
  EZK: { en: "Ezekiel", pt: "Ezequiel" },
  DAN: { en: "Daniel", pt: "Daniel" },
  HOS: { en: "Hosea", pt: "Oseias" },
  JOL: { en: "Joel", pt: "Joel" },
  AMO: { en: "Amos", pt: "Amós" },
  OBA: { en: "Obadiah", pt: "Obadias" },
  JON: { en: "Jonah", pt: "Jonas" },
  MIC: { en: "Micah", pt: "Miqueias" },
  NAM: { en: "Nahum", pt: "Naum" },
  HAB: { en: "Habakkuk", pt: "Habacuque" },
  ZEP: { en: "Zephaniah", pt: "Sofonias" },
  HAG: { en: "Haggai", pt: "Ageu" },
  ZEC: { en: "Zechariah", pt: "Zacarias" },
  MAL: { en: "Malachi", pt: "Malaquias" },
  // Deuterocanónicos
  "1ES": { en: "1 Esdras", pt: "1 Esdras" },
  "2ES": { en: "2 Esdras", pt: "2 Esdras" },
  TOB: { en: "Tobit", pt: "Tobias" },
  JDT: { en: "Judith", pt: "Judite" },
  WIS: { en: "Wisdom", pt: "Sabedoria" },
  SIR: { en: "Sirach", pt: "Eclesiástico (Sirácida)" },
  BAR: { en: "Baruch", pt: "Baruc" },
  BEL: { en: "Bel and the Dragon", pt: "Bel e o Dragão" },
  ESG: { en: "Esther (Greek)", pt: "Ester (Grego)" },
  MAN: { en: "Prayer of Manasseh", pt: "Oração de Manassés" },
  "1MA": { en: "1 Maccabees", pt: "1 Macabeus" },
  "2MA": { en: "2 Maccabees", pt: "2 Macabeus" },
  S3Y: { en: "Song of the Three Young Men", pt: "Cântico dos Três Jovens" },
  SUS: { en: "Susanna", pt: "Susana" },
  // Novo Testamento
  MAT: { en: "Matthew", pt: "Mateus" },
  MRK: { en: "Mark", pt: "Marcos" },
  LUK: { en: "Luke", pt: "Lucas" },
  JHN: { en: "John", pt: "João" },
  ACT: { en: "Acts", pt: "Atos" },
  ROM: { en: "Romans", pt: "Romanos" },
  "1CO": { en: "1 Corinthians", pt: "1 Coríntios" },
  "2CO": { en: "2 Corinthians", pt: "2 Coríntios" },
  GAL: { en: "Galatians", pt: "Gálatas" },
  EPH: { en: "Ephesians", pt: "Efésios" },
  PHP: { en: "Philippians", pt: "Filipenses" },
  COL: { en: "Colossians", pt: "Colossenses" },
  "1TH": { en: "1 Thessalonians", pt: "1 Tessalonicenses" },
  "2TH": { en: "2 Thessalonians", pt: "2 Tessalonicenses" },
  "1TI": { en: "1 Timothy", pt: "1 Timóteo" },
  "2TI": { en: "2 Timothy", pt: "2 Timóteo" },
  TIT: { en: "Titus", pt: "Tito" },
  PHM: { en: "Philemon", pt: "Filemom" },
  HEB: { en: "Hebrews", pt: "Hebreus" },
  JAS: { en: "James", pt: "Tiago" },
  "1PE": { en: "1 Peter", pt: "1 Pedro" },
  "2PE": { en: "2 Peter", pt: "2 Pedro" },
  "1JN": { en: "1 John", pt: "1 João" },
  "2JN": { en: "2 John", pt: "2 João" },
  "3JN": { en: "3 John", pt: "3 João" },
  JUD: { en: "Jude", pt: "Judas" },
  REV: { en: "Revelation", pt: "Apocalipse" },
}

export function bookDisplayName(code: string, lang: string): string {
  const entry = BOOK_NAMES[code]
  if (!entry) return code
  return lang === "pt" ? entry.pt : entry.en
}
